export const AuthorsJSON = {
  'numFound': 8486159,
  'start': 0,
  'numFoundExact': true,
  'docs': [{
    'key': 'OL4529419A',
    'text': ['/authors/OL4529419A', 'United States. Congress. House', 'United States. Congress. House.', 'United States. Congress House.', 'United States. Congress House', 'United States Congress House ', 'United States Congress. House '],
    'type': 'author',
    'name': 'United States. Congress. House',
    'alternate_names': ['United States. Congress. House.', 'United States. Congress House.', 'United States. Congress House', 'United States Congress House ', 'United States Congress. House '],
    'top_work': 'Post-Office appropriation bill',
    'work_count': 35779,
    'top_subjects': ['United States', 'United States', 'Claims', 'United States. Congress', 'Private Bills', 'Bills, Private', 'Public lands', 'Public buildings', 'Law and legislation', 'Public Expenditures'],
    '_version_': 1700762868179271682,
  }, {
    'key': 'OL539875A',
    'text': ['/authors/OL539875A', 'Philip M. Parker', 'philip M. Parker', 'Philip Parker'],
    'type': 'author',
    'name': 'Philip M. Parker',
    'alternate_names': ['philip M. Parker', 'Philip Parker'],
    'birth_date': 'June 20, 1960',
    'top_work': 'Webster\'s English to Portuguese Crossword Puzzles',
    'work_count': 34084,
    'top_subjects': ['Protected DAISY', 'Accessible book', 'Bibliography', 'Dictionaries', 'Computer network resources', 'MEDICAL', 'Popular works', 'HEALTH & FITNESS', 'Research', 'Diseases'],
    '_version_': 1700766761315467276,
  }, {
    'key': 'OL2656742A',
    'text': ['/authors/OL2656742A', 'Rand McNally', 'Rand Mcnally', 'Rand McNally & Company', 'Rand McNally and Company', 'Rand Mcnally & Company', 'Rand McNally Staff', 'Rand McNally.', 'Rand McNally Inc.', 'Rand McNally Editors', 'McNally & co Rand', 'McNally Rand', 'Rand McNally and Company.', 'Rand McNally & Co.', 'Rand McNally Co.', 'Rand McNally & Co', 'Rand McNally & Company.', 'Rand McNally Corp', 'Rand McNally, Inc.', 'Rand McNally Editord', 'Rand McNally Company', 'RandMcNally and Company.', 'McNally & company Rand', 'Rand McNally and Compay', 'Inc Rand McNally', 'Rand, McNally & co., pub', 'Rand, McNally and Company.', 'RAND McNALLY & COMPANY.', 'Rand mcNally & company.'],
    'type': 'author',
    'name': 'Rand McNally',
    'alternate_names': ['Rand Mcnally', 'Rand McNally & Company', 'Rand McNally and Company', 'Rand Mcnally & Company', 'Rand McNally Staff', 'Rand McNally.', 'Rand McNally Inc.', 'Rand McNally Editors', 'McNally & co Rand', 'McNally Rand', 'Rand McNally and Company.', 'Rand McNally & Co.', 'Rand McNally Co.', 'Rand McNally & Co', 'Rand McNally & Company.', 'Rand McNally Corp', 'Rand McNally, Inc.', 'Rand McNally Editord', 'Rand McNally Company', 'RandMcNally and Company.', 'McNally & company Rand', 'Rand McNally and Compay', 'Inc Rand McNally', 'Rand, McNally & co., pub', 'Rand, McNally and Company.', 'RAND McNALLY & COMPANY.', 'Rand mcNally & company.'],
    'birth_date': '1856',
    'top_work': 'UK Continental Shelf Oil Well Records',
    'work_count': 29390,
    'top_subjects': ['Great Britain', 'Law and legislation', 'Great Britain', 'Accessible book', 'United States', 'Colonies', 'England', 'Protected DAISY', 'Commerce', 'Maps'],
    '_version_': 1700754981850710045,
  }, {
    'key': 'OL2727133A',
    'text': ['/authors/OL2727133A', 'ICON Group Ltd.'],
    'type': 'author',
    'name': 'ICON Group Ltd.',
    'top_work': '(Financial Performance Series)',
    'work_count': 27885,
    'top_subjects': ['Statistical Analysis', 'General', 'Forecasting', 'Financial Analysis', 'Business / Economics / Finance', 'Company Study.', 'Labor Productivity', 'Human Resources.', 'Company Study'],
    '_version_': 1700755122249793545,
  }, {
    'key': 'OL18485A',
    'text': ['/authors/OL18485A', 'United States', 'USA', 'US', 'America', 'United States.', 'United States', 'Us Government', 'U.S. Government', 'US Government', 'US GOVERNMENT'],
    'type': 'author',
    'name': 'United States',
    'alternate_names': ['USA', 'US', 'America', 'United States.', 'United States', 'Us Government', 'U.S. Government', 'US Government', 'US GOVERNMENT'],
    'birth_date': 'July 4, 1776',
    'top_work': 'Pakistan',
    'work_count': 23667,
    'top_subjects': ['United States', 'Law and legislation', 'United States', 'Accessible book', 'Appropriations and expenditures', 'Finance', 'Government policy', 'Prevention', 'Management', 'Legal status, laws'],
    '_version_': 1700751662591770639,
  }, {
    'key': 'OL2727138A',
    'text': ['/authors/OL2727138A', 'ICON Group International, Inc.', 'Icon Group International, Inc. Staff', 'Icon Group International', 'Icon Group'],
    'type': 'author',
    'name': 'ICON Group International, Inc.',
    'alternate_names': ['Icon Group International, Inc. Staff', 'Icon Group International', 'Icon Group'],
    'top_work': 'The 2000-2005 Outlook for Men',
    'work_count': 15960,
    'top_subjects': ['Accessible book'],
    '_version_': 1700755122294882312,
  }, {
    'key': 'OL5631454A',
    'text': ['/authors/OL5631454A', 'No name', 'Sine Nomine'],
    'type': 'author',
    'name': 'No name',
    'alternate_names': ['Sine Nomine'],
    'top_work': 'Smart structures and materials 2003',
    'work_count': 15770,
    'top_subjects': ['Accessible book', 'Protected DAISY', 'genealogy', 'History', 'Congresses', 'thy', 'cases', 'medical', 'tbe', 'tlie'],
    '_version_': 1700767722945642498,
  }, {
    'key': 'OL2336667A',
    'text': ['/authors/OL2336667A', 'United States. Congress. Senate. Committee on Pensions'],
    'type': 'author',
    'name': 'United States. Congress. Senate. Committee on Pensions',
    'top_work': 'Old-Age Pensions',
    'work_count': 14131,
    'top_subjects': ['United States', 'Military pensions', 'Law and legislation', 'History', 'Claims vs. United States', 'Civil War, 1861-1865', 'Veterans', 'United States Civil War, 1861-1865', 'Revolution, 1775-1783', 'Spanish-American War, 1898'],
    '_version_': 1700753550611578886,
  }, {
    'key': 'OL4489781A',
    'text': ['/authors/OL4489781A', 'United States. General Accounting Office', 'United States. General Accounting Office.', 'United States General Accounting Office.', 'United States. General of Accounting Office.', 'United States. General Accounting OFfice.', 'United States General Accounting Office ', 'General Accounting Office (U.S.)', 'General Accounting Office.', 'U.S. General Accounting Office.', 'General Accountability Office (U.S.)', 'U S. General Accounting Office', 'U.S. General Accounting Office'],
    'type': 'author',
    'name': 'United States. General Accounting Office',
    'alternate_names': ['United States. General Accounting Office.', 'United States General Accounting Office.', 'United States. General of Accounting Office.', 'United States. General Accounting OFfice.', 'United States General Accounting Office ', 'General Accounting Office (U.S.)', 'General Accounting Office.', 'U.S. General Accounting Office.', 'General Accountability Office (U.S.)', 'U S. General Accounting Office', 'U.S. General Accounting Office'],
    'top_work': 'Financial audit',
    'work_count': 12513,
    'top_subjects': ['United States', 'United States', 'Management', 'Evaluation', 'Finance', 'Appropriations and expenditures', 'United States. Dept. of Defense', 'Armed Forces', 'Procurement', 'Costs'],
    '_version_': 1700762687297814548,
  }, {
    'key': 'OL2754228A',
    'text': ['/authors/OL2754228A', 'RH Value Publishing', 'Value Publ Rh', 'Random House Value Publishing', 'Value Publishing Rh', 'Rh Value Publishing'],
    'type': 'author',
    'name': 'RH Value Publishing',
    'alternate_names': ['Value Publ Rh', 'Random House Value Publishing', 'Value Publishing Rh', 'Rh Value Publishing'],
    'top_work': 'Light a penny candle',
    'work_count': 10696,
    'top_subjects': ['Accessible book', 'Protected DAISY', 'Pictorial works', 'History', 'Fiction', 'Biography', 'Cooking', 'Juvenile literature', 'Non-Classifiable', 'Juvenile fiction'],
    '_version_': 1700755354454851588,
  }],
}