export const AuthorsJSON = {
  'numFound': 1, 'start': 0, 'numFoundExact': true, 'docs': [{
    'key': 'OL23919A',
    'text': ['/authors/OL23919A', 'J. K. Rowling', 'Joanne Rowling', 'Joanne K. Rowling', 'J.K.Rowling', 'Rowling, J.K.', 'J. Rowling', 'Rowling, Joanne K.', 'Jo Murray', 'J K Rowling', 'Rowling J.K.', 'J.K. Rowling (author)', 'Rowling Joanne', 'J.K. Rowling', 'J.K. ROWLING', 'Rowling J K', 'J K ROWLING', 'Newt Scamander', 'JOANNE K. ROWLING', 'Kennilworthy Whisp', 'JK Rowling', 'JK Rowlings', 'jk rowling', 'R.K Rowling', 'J. K Rowling', 'J.K Rowling', 'Rowling J. K.', 'J. K. Rowling (Auteur)', 'J.k. Rowling', 'Rowling, J. K.', 'ROWLING J.K. -', 'J. K. ROWLING', 'Rowling,J.K.', 'J. K. Rowling', 'Robert Galbraith', 'Robert Galbraith (J.K. Rowling)'],
    'type': 'author',
    'name': 'J. K. Rowling',
    'alternate_names': ['Joanne Rowling', 'Joanne K. Rowling', 'J.K.Rowling', 'Rowling, J.K.', 'J. Rowling', 'Rowling, Joanne K.', 'Jo Murray', 'J K Rowling', 'Rowling J.K.', 'J.K. Rowling (author)', 'Rowling Joanne', 'J.K. Rowling', 'J.K. ROWLING', 'Rowling J K', 'J K ROWLING', 'Newt Scamander', 'JOANNE K. ROWLING', 'Kennilworthy Whisp', 'JK Rowling', 'JK Rowlings', 'jk rowling', 'R.K Rowling', 'J. K Rowling', 'J.K Rowling', 'Rowling J. K.', 'J. K. Rowling (Auteur)', 'J.k. Rowling', 'Rowling, J. K.', 'ROWLING J.K. -', 'J. K. ROWLING', 'Rowling,J.K.', 'J. K. Rowling', 'Robert Galbraith', 'Robert Galbraith (J.K. Rowling)'],
    'birth_date': '31 July 1965',
    'top_work': 'Harry Potter and the Philosopher\'s Stone',
    'work_count': 224,
    'top_subjects': ['Accessible book', 'Protected DAISY', 'Fiction', 'Harry Potter', 'Children\'s fiction', 'Wizards, fiction', 'England', 'Wizards', 'Magic', 'Fantasy fiction'],
    '_version_': 1705097936033021952,
  },
    {
      'key': 'OL34184A',
      'text': ['/authors/OL34184A', 'Roald Dahl', 'Dahl', 'R Dahl', 'Dahl Roald', 'Roald/Blake Qu Dahl', 'Roald (Hrsg.) Dahl', 'dahl,roald', 'Roald Dahls', 'Roald Dahl (1916-1990)', 'ROALD DAHL', 'Roald Dahl ( LUO ER DE DA ER )', 'R. Dahl', 'Roald Dahl,Roald Dahl', 'RoaldDahl', 'Dahl,Roald', 'DAHL,ROALD', 'Roald; Dahl', 'Poald Dahl'],
      'type': 'author',
      'name': 'Roald Dahl',
      'alternate_names': ['Dahl', 'R Dahl', 'Dahl Roald', 'Roald/Blake Qu Dahl', 'Roald (Hrsg.) Dahl', 'dahl,roald', 'Roald Dahls', 'Roald Dahl (1916-1990)', 'ROALD DAHL', 'Roald Dahl ( LUO ER DE DA ER )', 'R. Dahl', 'Roald Dahl,Roald Dahl', 'RoaldDahl', 'Dahl,Roald', 'DAHL,ROALD', 'Roald; Dahl', 'Poald Dahl'],
      'birth_date': '13 September 1916',
      'death_date': '23 November 1990',
      'top_work': 'Charlie and the Chocolate Factory',
      'work_count': 370,
      'top_subjects': ['Accessible book', 'Protected DAISY', 'Fiction', 'short story', 'Children\'s fiction', 'Juvenile fiction', 'Short stories', 'Humorous stories', 'London', 'Paris'],
      '_version_': 1704752513039728640,
    },
  ],
}

export const Author = [
  {
    'birth_date': '31 July 1965',
    'photos': [5543033, - 1],
    'title': 'OBE',
    'links': [{'url': 'http://www.jkrowling.com/', 'type': {'key': '/type/link'}, 'title': 'Official Site'}],
    'bio': {
      'type': '/type/text',
      'value': 'Joanne "Jo" Murray, OBE (n\u00e9e Rowling), better known under the pen name J. K. Rowling, is a British author best known as the creator of the Harry Potter fantasy series, the idea for which was conceived whilst on a train trip from Manchester to London in 1990. The Potter books have gained worldwide attention, won multiple awards, sold more than 400 million copies, and been the basis for a popular series of films.',
    },
    'source_records': ['amazon:8893817055', 'amazon:4863895666', 'amazon:1526618249', 'amazon:8862561512', 'amazon:1526618230', 'amazon:6073193009', 'amazon:0747574286', 'amazon:8327158775'],
    'alternate_names': ['Joanne Rowling', 'Joanne K. Rowling', 'J.K.Rowling', 'Rowling, J.K.', 'J. Rowling', 'Rowling, Joanne K.', 'Jo Murray', 'J K Rowling', 'Rowling J.K.', 'J.K. Rowling (author)', 'Rowling Joanne', 'J.K. Rowling', 'J.K. ROWLING', 'Rowling J K', 'J K ROWLING', 'Newt Scamander', 'JOANNE K. ROWLING', 'Kennilworthy Whisp', 'JK Rowling', 'JK Rowlings', 'jk rowling', 'R.K Rowling', 'J. K Rowling', 'J.K Rowling', 'Rowling J. K.', 'J. K. Rowling (Auteur)', 'J.k. Rowling', 'Rowling, J. K.', 'ROWLING J.K. -', 'J. K. ROWLING', 'Rowling,J.K.', 'J. K. Rowling', 'Robert Galbraith', 'Robert Galbraith (J.K. Rowling)'],
    'remote_ids': {'viaf': '116796842', 'wikidata': 'Q34660', 'isni': '000000012148628X'},
    'entity_type': 'person',
    'wikipedia': 'http://en.wikipedia.org/wiki/J._K._Rowling',
    'name': 'J. K. Rowling',
    'personal_name': 'J. K. Rowling',
    'key': '/authors/OL23919A',
    'type': {'key': '/type/author'},
    'latest_revision': 49,
    'revision': 49,
    'created': {'type': '/type/datetime', 'value': '2008-04-01T03:28:50.625462'},
    'last_modified': {'type': '/type/datetime', 'value': '2021-07-12T16:41:47.129973'},
  },
  {
    'key': '/authors/OL34184A',
    'bio': {
      'type': '/type/text',
      'value': 'Roald Dahl was a British novelist, short story writer, and screenwriter.\r\n\r\nBorn in north Cardiff, Wales, to Norwegian parents, Dahl served in the Royal Air Force during the Second World War, in which he became a flying ace and intelligence agent. He rose to prominence in the 1940s with works for both children and adults, and became one of the world\'s bestselling authors. His short stories are known for their unexpected endings, and his children\'s books for their unsentimental, often very dark humour. ([Source][1].)\r\n\r\n\r\n  [1]: http://en.wikipedia.org/wiki/Roald_Dahl',
    },
    'links': [{
      'url': 'http://www.roalddahl.com/',
      'type': {'key': '/type/link'},
      'title': 'roalddahl.com',
    }, {'url': 'http://en.wikipedia.org/wiki/Roald_Dahl', 'type': {'key': '/type/link'}, 'title': 'Wikipedia entry'}],
    'type': {'key': '/type/author'},
    'name': 'Roald Dahl',
    'personal_name': 'Dahl, Roald.',
    'source_records': ['amazon:8420440248', 'amazon:8420401307', 'amazon:0670852503', 'amazon:0140386068', 'amazon:0140382518', 'amazon:7533299299'],
    'remote_ids': {'viaf': '108159131', 'wikidata': 'Q25161', 'isni': '0000000121468188'},
    'birth_date': '13 September 1916',
    'alternate_names': ['Dahl', 'R Dahl', 'Dahl Roald', 'Roald/Blake Qu Dahl', 'Roald (Hrsg.) Dahl', 'dahl,roald', 'Roald Dahls', 'Roald Dahl (1916-1990)', 'ROALD DAHL', 'Roald Dahl ( LUO ER DE DA ER )', 'R. Dahl', 'Roald Dahl,Roald Dahl', 'RoaldDahl', 'Dahl,Roald', 'DAHL,ROALD', 'Roald; Dahl', 'Poald Dahl'],
    'death_date': '23 November 1990',
    'photos': [9395323, 9395316, 9395314, 9395313, 6287214],
    'latest_revision': 28,
    'revision': 28,
    'created': {'type': '/type/datetime', 'value': '2008-04-01T03:28:50.625462'},
    'last_modified': {'type': '/type/datetime', 'value': '2021-07-08T21:11:20.525635'},
  },
]