export const description = [
  {
    'description': 'Harry Potter #1\r\n\r\nWhen mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry.\r\n\r\nThey are swiftly confiscated by his aunt and uncle.\r\n\r\nThen, on Harry\u2019s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts.\r\n\r\nAnd so the first of the Harry Potter adventures is set to begin.\r\n([source][1])\r\n\r\n\r\n  [1]: https://www.jkrowling.com/book/harry-potter-philosophers-stone/',
    'links': [{
      'url': 'https://www.jkrowling.com/book/harry-potter-philosophers-stone/',
      'title': 'Harry Potter and the Philosopher\'s Stone - J.K. Rowling',
      'type': {'key': '/type/link'},
    }, {
      'title': 'Harry Potter and the Philosopher\'s Stone - Wikipedia',
      'url': 'https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone',
      'type': {'key': '/type/link'},
    }, {
      'url': 'https://www.theguardian.com/childrens-books-site/2015/jul/29/harry-potter-and-the-philosophers-stone-j-k-rowling-review',
      'title': 'Harry Potter and the Philosopher\'s Stone by J.K. Rowling \u2013 review (theguardian.com)',
      'type': {'key': '/type/link'},
    }, {
      'url': 'https://www.theguardian.com/childrens-books-site/2015/mar/01/review-j-k-rowling-harry-potter-philosophers-stone',
      'title': 'Harry Potter and the Philosopher\'s Stone by J.K. Rowling - review (theguardian.com)',
      'type': {'key': '/type/link'},
    }],
    'title': 'Harry Potter and the Philosopher\'s Stone',
    'covers': [10521270, 8266542, 9383496, 10217621, 10484589, 10484588, 10515101, 1020319, 10469774, 10513095, 10485032, 10447552, - 1, 10864265],
    'subject_places': ['England', 'Hogwarts School of Witchcraft and Wizardry', '4 Privet Drive', 'Diagon Alley', 'Leaky Cauldron', 'Gringotts Wizarding Bank', 'Forbidden Forest', 'King\'s Cross Station', 'Platform Nine and Three-quarters'],
    'subject_people': ['Harry Potter', 'Ron Weasley', 'Hermione Granger', 'Neville Longbottom', 'Rubeus Hagrid', 'Albus Dumbledore', 'Minerva McGonagall', 'Nicolas Flamel', 'Norbert', 'Sorting Hat', 'Severus Snape', 'Quirinus Quirrell', 'Petunia Dursley', 'Draco Malfoy', 'Argus Filch', 'Vernon Dursley', 'Dudley Dursley', 'Fred Weasley', 'George Weasley', 'Jorge', 'Ginny Weasley', 'Gina', 'Molly Weasley', 'Percy Weasley', 'Vincent Crabbe', 'Gregory Goyle', 'Lee Jordan', 'Scabbers', 'Hannah Abbott', 'Bloody Baron', 'Susan Bones', 'Terry Boot', 'Mandy Brocklehurst', 'Lavender Brown', 'Millicent Bulstrode', 'Nearly Headless Nick', 'Fat Friar', 'Fat Lady', 'Justin Finch-Fetchley', 'Seamus Finnigan', 'Morag MacDougal', 'Lily Moon', 'Pansy Parkinson', 'Padma Patil', 'Parvati Patil', 'Chap\u00e9u Seletor', 'Peeves', 'Dean Thomas', 'Lisa Turpin', 'Blaise Zabini', 'Lil\u00e1', 'Harry Potter (Fictitious character)', 'Hermine Granger', 'Ron Weasly'],
    'key': '/works/OL82563W',
    'authors': [{'author': {'key': '/authors/OL23919A'}, 'type': {'key': '/type/author_role'}}],
    'excerpts': [{
      'comment': 'first sentence',
      'author': {'key': '/people/seabelis'},
      'excerpt': 'Mr. And Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much.',
    }],
    'type': {'key': '/type/work'},
    'subjects': ['Ghosts', 'Monsters', 'Vampires', 'Witches', 'Challenges and Overcoming Obstacles', 'Magic and Supernatural', 'Cleverness', 'School Life', 'school stories', 'Wizards', 'Magic', 'MAGIA', 'MAGOS', 'Juvenile fiction', 'Fiction', 'NOVELAS INGLESAS', 'Schools', 'orphans', 'fantasy fiction', 'England in fiction', 'Witches in fiction', 'Wizards in fiction', 'Alchemy', 'New York Times bestseller', 'Juvenile literature', 'Magic in fiction', 'Open Library Staff Picks', 'Juvenile audience', 'Children\'s stories', 'Juvenile works', 'Schools in fiction', 'Fantasy', 'Hogwarts School of Witchcraft and Wizardry (Imaginary place)', 'Harry Potter (Fictitious character)', 'Ficci\u00f3n juvenil', 'Escuelas', 'Hogwarts School of Witchcraft and Wizardry (Imaginary organization)', 'Translations from English', 'Chinese fiction', 'Hermione Granger (Fictitious character)', 'Reading Level-Grade 9', 'Reading Level-Grade 11', 'Reading Level-Grade 10', 'Reading Level-Grade 12', 'Hogwarts school of witchcraft and wizardry (imaginary organization), fiction', 'Children\'s fiction', 'Schools, fiction', 'England, fiction', 'Potter, harry (fictitious character), fiction', 'Wizards, fiction', 'Magic, fiction', 'Fiction, fantasy, general', 'Large type books', 'Magier', 'Fabeltiere', 'Lehrling', 'Kinderbuch', 'Stein der Weisen', 'Ungeheuer', 'Junge', 'English language', 'Translating into Welsh', 'Modern history to 20th century: c 1700 to c 1900', 'Literary theory', 'English literature', 'Ron Weasley (Fictitious character)', 'Latin language materials'],
    'latest_revision': 84,
    'revision': 84,
    'created': {'type': '/type/datetime', 'value': '2009-10-17T07:07:29.461716'},
    'last_modified': {'type': '/type/datetime', 'value': '2021-07-02T12:05:07.248484'},
  },
  {
    'description': 'The main character of Fantastic Mr. Fox is an extremely clever anthropomorphized fox named Mr. Fox. He lives with his wife and four little foxes. In order to feed his family, he steals food from the cruel, brutish farmers named Boggis, Bunce, and Bean every night.\r\n\r\nFinally tired of being constantly outwitted by Mr. Fox, the farmers attempt to capture and kill him. The foxes escape in time by burrowing deep into the ground. The farmers decide to wait outside the hole for the foxes to emerge. Unable to leave the hole and steal food, Mr. Fox and his family begin to starve. Mr. Fox devises a plan to steal food from the farmers by tunneling into the ground and borrowing into the farmer\'s houses.\r\n\r\nAided by a friendly Badger, the animals bring the stolen food back and Mrs. Fox prepares a great celebratory banquet attended by the other starving animals and their families. Mr. Fox invites all the animals to live with him underground and says that he will provide food for them daily thanks to his underground passages. All the animals live happily and safely, while the farmers remain waiting outside in vain for Mr. Fox to show up.',
    'title': 'Fantastic Mr. Fox',
    'covers': [6498519, 8904777, 108274, 233884, 1119236, - 1, 10222599, 10482837, 3216657],
    'subject_places': ['English countryside'],
    'subjects': ['Animals', 'Hunger', 'Open Library Staff Picks', 'Juvenile fiction', 'Children\'s stories, English', 'Foxes', 'Fiction', 'Zorros', 'Ficci\u00f3n juvenil', 'Tunnels', 'Interviews', 'Farmers', 'Children\'s stories', 'Rats', 'Welsh Authors', 'English Authors', 'Thieves', 'Tricksters', 'Badgers', 'Children\'s fiction', 'Foxes, fiction', 'Underground', 'Renards', 'Romans, nouvelles, etc. pour la jeunesse'],
    'subject_people': ['Bean', 'Boggis', 'Bunce', 'Mr Fox'],
    'key': '/works/OL45883W',
    'authors': [{'author': {'key': '/authors/OL34184A'}, 'type': {'key': '/type/author_role'}}],
    'subject_times': ['20th Century'],
    'type': {'key': '/type/work'},
    'latest_revision': 44,
    'revision': 44,
    'created': {'type': '/type/datetime', 'value': '2009-10-15T11:34:21.437031'},
    'last_modified': {'type': '/type/datetime', 'value': '2021-07-13T06:30:02.285112'},
  },
]
